- name: 언니의파우치 (Android)
  link: https://play.google.com/store/apps/details?id=com.ui.monyapp&hl=ko
  icon: ion-social-android

- name: 언니의파우치 (iOS)
  link: https://itunes.apple.com/kr/app/eonniuipauchi/id976126416
  icon: ion-social-apple

- name: 언니의파우치 (Web)
  link: https://www.unpa.me
  icon: ion-android-desktop